// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDm_j3UG2E1Cs7L1Ub0N0axfTcIao5XTII',
    appId: '1:184844856033:web:5f80fa9bd4ec6030fe25a0',
    messagingSenderId: '184844856033',
    projectId: 'ecomitra-71a79',
    authDomain: 'ecomitra-71a79.firebaseapp.com',
    databaseURL: 'https://ecomitra-71a79-default-rtdb.firebaseio.com',
    storageBucket: 'ecomitra-71a79.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAstHTj_c4Fo7ziJK93amQ2nyeCs8M3Xg8',
    appId: '1:184844856033:android:83588a1bef7db90ffe25a0',
    messagingSenderId: '184844856033',
    projectId: 'ecomitra-71a79',
    databaseURL: 'https://ecomitra-71a79-default-rtdb.firebaseio.com',
    storageBucket: 'ecomitra-71a79.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCn0MTWOnL4_qHA_Mku-B88k5t8n2qvsYI',
    appId: '1:184844856033:ios:854dd0ecd9580f9bfe25a0',
    messagingSenderId: '184844856033',
    projectId: 'ecomitra-71a79',
    databaseURL: 'https://ecomitra-71a79-default-rtdb.firebaseio.com',
    storageBucket: 'ecomitra-71a79.firebasestorage.app',
    iosBundleId: 'com.example.ecoMitra',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCn0MTWOnL4_qHA_Mku-B88k5t8n2qvsYI',
    appId: '1:184844856033:ios:854dd0ecd9580f9bfe25a0',
    messagingSenderId: '184844856033',
    projectId: 'ecomitra-71a79',
    databaseURL: 'https://ecomitra-71a79-default-rtdb.firebaseio.com',
    storageBucket: 'ecomitra-71a79.firebasestorage.app',
    iosBundleId: 'com.example.ecoMitra',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDm_j3UG2E1Cs7L1Ub0N0axfTcIao5XTII',
    appId: '1:184844856033:web:6601f0c7f01ce86ffe25a0',
    messagingSenderId: '184844856033',
    projectId: 'ecomitra-71a79',
    authDomain: 'ecomitra-71a79.firebaseapp.com',
    databaseURL: 'https://ecomitra-71a79-default-rtdb.firebaseio.com',
    storageBucket: 'ecomitra-71a79.firebasestorage.app',
  );
}
